name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Ananttyagi07
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community
          plugin_languages: yes
          plugin_stars: yes
